#!/usr/bin/env python3
"""Build a non-empty plan-view SVG polyline from Blender OBJ vertices (vx, vz plane).

Blender's Grease Pencil SVG export can produce an empty file; this uses the same curve as catenaries.obj.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def load_vertices_obj(path: Path) -> list[tuple[float, float, float]]:
    verts: list[tuple[float, float, float]] = []
    with path.open(encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith("v "):
                parts = line.split()
                verts.append((float(parts[1]), float(parts[2]), float(parts[3])))
    return verts


def main() -> int:
    ap = argparse.ArgumentParser(description="OBJ vertices → 2D SVG polyline (plan: X–Z)")
    ap.add_argument(
        "obj",
        nargs="?",
        default=str(Path(__file__).resolve().parent.parent / "3D Files" / "catenaries.obj"),
        help="Path to .obj",
    )
    ap.add_argument(
        "-o",
        "--output",
        default=str(Path(__file__).resolve().parent.parent / "3D Files" / "catenaries.svg"),
        help="Output .svg path",
    )
    ap.add_argument("--max-points", type=int, default=6000, help="Decimate to at most this many vertices")
    args = ap.parse_args()

    obj_path = Path(args.obj)
    if not obj_path.is_file():
        print(f"Missing OBJ: {obj_path}", file=sys.stderr)
        return 1

    verts = load_vertices_obj(obj_path)
    if len(verts) < 2:
        print("Too few vertices", file=sys.stderr)
        return 1

    step = max(1, len(verts) // args.max_points)
    verts = verts[::step]

    xs = [v[0] for v in verts]
    zs = [v[2] for v in verts]
    minx, maxx = min(xs), max(xs)
    minz, maxz = min(zs), max(zs)
    span = max(maxx - minx, maxz - minz, 1e-9)
    pad = 0.03 * span
    w = maxx - minx + 2 * pad
    h = maxz - minz + 2 * pad
    stroke = max(0.02, span * 0.002)

    def sx(x: float) -> float:
        return x - minx + pad

    def sy(z: float) -> float:
        return h - (z - minz + pad)

    pts = " ".join(f"{sx(v[0]):.5f},{sy(v[2]):.5f}" for v in verts)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    svg = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w:.6f}" height="{h:.6f}" viewBox="0 0 {w:.6f} {h:.6f}">
  <title>Catenary from OBJ (plan projection: vertex X vs Z)</title>
  <desc>Generated by tools/obj_to_plan_svg.py — not Blender Grease Pencil export.</desc>
  <rect fill="#1a1a22" x="0" y="0" width="{w:.6f}" height="{h:.6f}" />
  <polyline fill="none" stroke="#dd9944" stroke-width="{stroke:.6f}" points="{pts}" />
</svg>
"""
    out_path.write_text(svg, encoding="utf-8")
    print(f"Wrote {out_path} ({len(verts)} points)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
